# Quickstart SPARSE

## Instalation

```bash
pip install sparse_pkg_rojo1997
```

## Examples

We will try to illustrate how we can work with this module in the same way that we worked with Numpy.

In [1]:
import numpy as np
import sparse

Let's start by creating a random matrix of integers in Numpy:

In [2]:
M1 = np.random.randint(
    low = 0,
    high = 5,
    size = (2,2,2,2)
)
M1

array([[[[1, 2],
         [0, 0]],

        [[1, 1],
         [0, 3]]],


       [[[1, 0],
         [2, 2]],

        [[4, 3],
         [2, 0]]]])

Now we can compute the sparse matrix from the dense matrix using *fill_value=0* as default value with the following lines:

In [3]:
M2 = sparse.from_numpy(M1, fill_value = 0)
print(M2)
print(np.count_nonzero(M1 != 0))

<sparse: shape=[2 2 2 2]>, dtype=int32, n0v=11, fill_value=0>
11


The result is a sparse matrix with the same dimensions. Not 0 Values is equal in both case.

Let's create a new sparse matrix using the *randint* function from sparse module:

In [4]:
M3 = sparse.random.randint(
    low = 1,
    high = 10,
    sparsity = 0.01,
    shape = (100,100,100),
    fill_value = 0
)
print(M3)

<sparse: shape=[100 100 100]>, dtype=<class 'numpy.float64'>, n0v=10000, fill_value=0>


There is an extra parameter called sparsity which tell us the proportion of values other than 0.

The elements of the matrix can be accessed using most of the techniques used in NumPy:

In [13]:
# 1) Access an element
#print(M3[0,1,2])
# 2) Submatrix slice
#print(M3[25:75,25:75,25:75])
# 3) Submetrix list
#print(M3[[2,3,5],[8,5,1,7,1],[9,3,5,3]])
# 4) Convinations
print(M3[40,:,[8,2,3]])
#print(M3[40,2:80:3,[8,2,3]])

KeyError: 7.0

In [6]:
from sys import getsizeof

M2 = M1.to_numpy()
print(getsizeof(M1))
print(getsizeof(M2))

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [6]:
M = sparse.zeros(shape = (100,100,100,100,100))
M[1,2,3,4,5] = 10
M[25:75,25:75,50,50,50] = 5

In [1]:
M[25:75,25:75,50,50,50].to_numpy().shape

NameError: name 'M' is not defined

In [2]:
M = sparse.zeros(shape = (10,10))
M[:10,:10] = 5
M.to_numpy()

(slice(None, 10, None), slice(None, 10, None))


array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [4]:
M1 = sparse.zeros(shape = (3,3,3))
M2 = sparse.ones(shape = (4,4))
print(M1[0,:,:].to_numpy())
M1[0,:,:] = M2
print(M1[0,:,:].to_numpy())


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
