# Quickstart SPARSE

## Instalation

```bash
pip install sparse
```

In [1]:
import numpy as np
import sparse

Create random sparse matrix

In [4]:
M1 = sparse.random.randint(
    low = 1,
    high = 10,
    sparsity = 0.01,
    shape = (100,100,100),
    fill_value = 0
)
print(M1)

<sparse: shape=[100 100 100]>, dtype=<class 'numpy.float64'>, n0v=10000, fill_value=0>


In [5]:
from sys import getsizeof

M2 = M1.to_numpy()
print(getsizeof(M1))
print(getsizeof(M2))

48
8000128


In [6]:
M = sparse.zeros(shape = (100,100,100,100,100))
M[1,2,3,4,5] = 10
M[25:75,25:75,50,50,50] = 5

In [5]:
M[25:75,25:75,50,50,50].to_numpy()

array([[5., 5., 5., ..., 5., 5., 5.],
       [5., 5., 5., ..., 5., 5., 5.],
       [5., 5., 5., ..., 5., 5., 5.],
       ...,
       [5., 5., 5., ..., 5., 5., 5.],
       [5., 5., 5., ..., 5., 5., 5.],
       [5., 5., 5., ..., 5., 5., 5.]])

In [2]:
M = sparse.zeros(shape = (10,10))
M[:10,:10] = 5
M.to_numpy()

(slice(None, 10, None), slice(None, 10, None))


array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [4]:
M1 = sparse.zeros(shape = (3,3,3))
M2 = sparse.ones(shape = (4,4))
print(M1[0,:,:].to_numpy())
M1[0,:,:] = M2
print(M1[0,:,:].to_numpy())


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
